{
 "title": "PrismDNS",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "DNS Requests",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(last_over_time(prismdns_dns_requests_total[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DNS Responses",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(last_over_time(prismdns_dns_responses_total[$__range]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Upstream Requests",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(last_over_time(prismdns_upstream_queries_total[$__range]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Upstream Responses",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(last_over_time(prismdns_upstream_responses_total[$__range]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "SERVFAIL Responses",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(last_over_time(prismdns_servfail_total[$__range]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Average Upstream Latency",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 1, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(last_over_time(prismdns_upstream_latency[$__range]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Upstream Outages",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 7, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(last_over_time(prismdns_upstream_health[$__range]) != 1)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Ratelimited Queries",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 13, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(last_over_time(prismdns_ratelimit_hits_total[$__range]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "NXDOMAIN Responses",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 18, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(last_over_time(prismdns_nxdomain_total[$__range]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Upstream Status",
   "type": "status-history",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "targets": [
    { "expr": "prismdns_upstream_health", "legendFormat": "{{instance}}: {{upstream}}" }
   ]
  },
  {
   "title": "Upstream Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expr": "prismdns_upstream_latency", "legendFormat": "{{instance}}: {{upstream}}" }
   ]
  },
  {
   "title": "Queries Received",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "increase(prismdns_dns_requests_total[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Queries Responded",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "increase(prismdns_dns_responses_total[$__rate_interval])",
     "legendFormat": "{{instance}}: {{rcode}}"
    }
   ]
  },
  {
   "title": "Upstream Queries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "increase(prismdns_upstream_queries_total[$__rate_interval])",
     "legendFormat": "{{instance}}: {{upstream}} {{protocol}}"
    }
   ]
  },
  {
   "title": "Upstream Responses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "expr": "increase(prismdns_upstream_responses_total[$__rate_interval])",
     "legendFormat": "{{instance}}: {{upstream}} {{rcode}}"
    }
   ]
  },
  {
   "title": "NXDOMAIN Responses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "increase(prismdns_nxdomain_total[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "SERVFAIL Responses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "targets": [
    {
     "expr": "increase(prismdns_servfail_total[$__rate_interval])",
     "legendFormat": "{{instance}}: {{cause}}"
    }
   ]
  },
  {
   "title": "Ratelimited Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 50 },
   "targets": [
    {
     "expr": "increase(prismdns_ratelimit_hits_total[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}