name: Publish release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  prepare-build:
    uses: TrueWinter/PrismDNS/.github/workflows/prepare-build.yml@main

  build-and-release-github:
    runs-on: ubuntu-latest
    needs: prepare-build
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          fetch-tags: true
      - name: Make the script files executable
        run: chmod +x ./build.sh ./.github/scripts/commit-log.sh
      - name: Build
        run: ./build.sh
        env:
          VERSION: ${{ needs.prepare-build.outputs.version }}
      - name: Get commit log
        run: ./.github/scripts/commit-log.sh > commits.log
      - name: Release
        uses: softprops/action-gh-release@v3
        with:
          files: dist/*
          body_path: commits.log


  build-and-release-docker:
    uses: TrueWinter/PrismDNS/.github/workflows/docker-release.yml@main
    needs: prepare-build
    with:
      version: ${{ needs.prepare-build.outputs.version }}
    secrets:
      dockerhub_username: ${{ secrets.dockerhub_username }}
      dockerhub_token: ${{ secrets.dockerhub_token }}
