name: Publish commit

on:
  push:
    branches: [main]

jobs:
  prepare-build:
    uses: TrueWinter/PrismDNS/.github/workflows/prepare-build.yml@main

  build-and-release:
    uses: TrueWinter/PrismDNS/.github/workflows/docker-release.yml@main
    needs: prepare-build
    with:
      version: ${{ needs.prepare-build.outputs.version }}
    secrets:
      dockerhub_username: ${{ secrets.dockerhub_username }}
      dockerhub_token: ${{ secrets.dockerhub_token }}
